name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v3

      - name: Show files for debug
        run: |
          ls -l
          cat ./test.bash
          ls -l ./syodou

      - name: Install bc
        run: sudo apt-get update && sudo apt-get install -y bc

      - name: Make syodou executable
        run: chmod +x ./syodou

      - name: Run all tests
        run: bash -xv ./test.bash

